### ISSUE TITLE
Implement create test email address + find test email

### ISSUE THREAD

**Issue by raphael-leger** [railsware/mailtrap-nodejs#1]
Hi, it would be great to implement those two basic features in this official node client for Mailtrap:

**1. Create test email addresses programmatically**
With [Ethereal Email](https://ethereal.email), we can generate a test email account with `nodemailer.createTestAccount()`, cf. [documentation](https://ethereal.email/help)
With [Mailosaur](https://mailosaur.com), there is no setup required and we can send emails to `[anything]@[domain].mailosaur.net`, cf. [documentation](https://mailosaur.com/docs/languages/nodejs/#4-find-an-email-for-automated-testing).
With Mailtrap, how can we achieve that? The documentation lacks this information.

**2. Find a test email programmatically**
With [Ethereal Email](https://ethereal.email), we can search an inbox with imap, cf. [code example](https://github.com/bahmutov/cypress-ethereal-email-example/blob/d5e8c66f20e9db9d2f3db23d7aceee2fb02cf73e/cypress/plugins/email-account.js#L39-L47)
With [Mailosaur](https://mailosaur.com), we can search an inbox with the node client, cf. [documentation](https://mailosaur.com/docs/languages/nodejs/#4-find-an-email-for-automated-testing).
With Mailtrap, how can we achieve that? The documentation lacks this information.

**Comment by leonid-shevtsov** [comment]
Hi! The present version of this package (v3) doesn't implement the testing API yet. However, you can still use former version 2 of the package to retrieve test inboxes and messages.

Also the package doesn't implement inbox creation. However, [creating an inbox is supported in our HTTP API](https://mailtrap.docs.apiary.io/#reference/project/apiv1companiesidinboxes/post). So, you can do it with a simple HTTP request. The API reference includes a JavaScript code sample.

The API response should contain everything you need to send mail, specifically the username and password.

And of course there is also support for deleting the inbox afterwards in the API.

The basic way to send mail to a MailTrap inbox is by directing it to our SMTP server with the inbox credentials. A designated _email address_ for the inbox is available as a paid feature. You can check its availability on your plan by the `email_username_enabled` flag in the API response. In that case, the `email_username` and `email_domain` fields constitute the inbox email address.
