### ISSUE TITLE
npm update for bulk API 

### ISSUE THREAD

**Issue by hua1995116** [railsware/mailtrap-nodejs#41]
The current npm version is still 3 months old and cannot support the latest bulk function.

**Comment by tudormarciu** [comment]
> The current npm version is still 3 months old and cannot support the latest bulk function.

Hi @hua1995116 thanks for the heads-up! We are currently working on adding Bulk stream support and we will release it soon.

**Comment by vittorius** [comment]
@hua1995116 Done! Feel free to update your `mailtrap` to v3.4.0.
